### ISSUE TITLE
Fun suggestion for binding

### ISSUE THREAD

**Issue by elliottkember** [carbocation/soulmate#1]
Best setup flow I can think of:

1. Open Soulmate website
2. Instructions on the site explain how to connect to your new light (change wifi)
3. Big button that says "ok I've done that"
4. Button navigates the browser to 192.168.1.4

**Comment by carbocation** [comment]
This is a good idea. Currently the soulmate code is running as part of a generic "tools" service that I run. Let me start by extracting it into this repo so we can all see it and manipulate it.
